In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta

#  Change Master, Glossary_content, Amagi, Dayparts

In [2]:
#Change Master And Month****************************************************************************

Master = pd.read_excel('Master ElRey - September.xlsx', sheet_name='Master ElRey - September')
glossary_content = pd.read_excel('Master ElRey - September.xlsx', sheet_name= 'Glossary')


Amagi_dp1=pd.read_csv('April_hourly_noContent.csv')
Amagi_dp2=pd.read_csv('May_hourly_noContent.csv')
Amagi_dp3=pd.read_csv('June_hourly_noContent.csv')
Amagi_dp4=pd.read_csv('July_hourly_noContent.csv')
Amagi_dp5=pd.read_csv('August_hourly_noContent.csv')

Amagi_dp6=pd.read_csv('September_hourly_noContent.csv')
Amagi=Amagi_dp6



glossary_channel =pd.read_excel('Glossary.xlsx', sheet_name='Platform_Channel')

In [3]:
Master

,Unnamed: 0,HOUR,SEGMENT ID,ASSET ID,SEASON ID,SEASON TITLE,ASSET ID.1,TYPE,TITLE,YEAR,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,1,2021-09-01 00:02:01:00,NaN,1000000000577,NaN,NaN,1000000000577,episode,Undocumented in America: Living in the Shadows,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2021-09-01 00:49:03:05,NaN,1000000000576,NaN,NaN,1000000000576,episode,Latinos and the Evolution of the Labor Movement,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2021-09-01 01:38:31:11,NaN,1000000000748,NaN,NaN,1000000000748,episode,No More A-Holes,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2021-09-01 02:03:47:13,NaN,CEG10031813,NaN,NaN,CEG10031813,feature_film,The Hills Have Eyes,1977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2021-09-01 03:44:37:27,NaN,CEG10031814,NaN,NaN,CEG10031814,feature_film,The Hills Have Eyes Part 2,1984,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,795,2021-09-30 19:51:54:03,NaN,CEG10027418,NaN,NaN,CEG10027418,episode,Episode 8,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
795,796,2021-09-30 20:43:34:09,NaN,CEG10027419,NaN,NaN,CEG10027419,episode,Episode 9,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,797,2021-09-30 21:34:41:06,NaN,CEG10027420,NaN,NaN,CEG10027420,episode,Episode 10,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,798,2021-09-30 22:26:04:29,NaN,CEG10026659,NaN,NaN,CEG10026659,episode,Episode 1,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,799,2021-09-30 23:15:27:02,NaN,1000000000597,NaN,NaN,1000000000597,episode,Latino Literature,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
glossary_content

                ID                                      TITLE Series/Film
0      CEG10016019                                     4GOT10        Film
1     883476022161                        ALONE IN THE DARK 2        Film
2     883476022161                        ALONE IN THE DARK 2        Film
3    1000000000783               Americanos - El Rey Original        Film
4      CEG10031907                                   Audition        Film
..             ...                                        ...         ...
431  1000000001392                           Miami Connection        Film
432   883476022161                        ALONE IN THE DARK 2        Film
433  1000000000785                                 On The Run        Film
434  1000000001030  Guy from Harlem (aka Good Guy From Harlem        Film
435  1000000000788                            Grandma's House        Film

[436 rows x 3 columns]

In [5]:
Amagi

,Date,Channel Name,Session Count,Total Viewership Minutes,Unique Viewers
0,9/1/2021 0:00,bloodydisgusting_littlstar,1,60,1
1,9/1/2021 0:00,Bloody Disgusting Roku US,1147,6871,949
2,9/1/2021 0:00,BloodyDisgusting_SelectTv,1,1,1
3,9/1/2021 0:00,Bloody Disgusting Vizio US,184,1372,140
4,9/1/2021 0:00,Bobross Plex,74,2404,62
...,...,...,...,...,...
48723,9/30/2021 23:00,Redbox Docurama,19,67,18
48724,9/30/2021 23:00,Redbox DoveNOW,14,133,14
48725,9/30/2021 23:00,soreal_littlstar,1,60,1
48726,9/30/2021 23:00,SoReal Plex,12,150,11
48727,9/30/2021 23:00,Towie Roku US,1294,3560,1029

In [6]:
glossary_channel

               Platform/Channel   Platform           Channel
0    bloodydisgusting_littlstar  Littlstar  BloodyDisgusting
1        BloodyDisgusting_OandO      OandO  BloodyDisgusting
2     Bloody Disgusting Roku US       Roku  BloodyDisgusting
3     BloodyDisgusting_SelectTv   SelectTv  BloodyDisgusting
4        BloodyDisgusting_Vizio      Vizio  BloodyDisgusting
..                          ...        ...               ...
126             FashionBox Plex       Plex        FashionBox
127               Gametoon Plex       Plex          Gametoon
128                 SoReal Plex       Plex            SoReal
129                Roku_bobross       Roku           BobRoss
130        ComedyDynamics_Vizio      Vizio    ComedyDynamics

[131 rows x 3 columns]

In [7]:
Master= Master.loc[:,('HOUR', 'ASSET ID')]
Master.rename(columns= {'ASSET ID': 'Content ID'},inplace=True)

In [8]:
glossary_content.rename(columns= {'ID': 'Content ID'}, inplace=True)
glossary_content = glossary_content[['Content ID', 'TITLE', 'Series/Film']]

# Merge Master with glossary

In [9]:
Master = pd.merge(Master, glossary_content, on = 'Content ID', how='left')

In [10]:
Master.rename(columns= {'TITLE':'Title'}, inplace=True)

# Datetime Adjustments

In [11]:
Master['TS'] = pd.to_datetime(Master['HOUR'], format = '%Y-%m-%d %H:%M:%S:%f')
Master= Master[['TS', 'Content ID', 'Title', 'Series/Film']]

In [12]:
Master['Hour_Start']= Master['TS'].dt.hour
Master['Minutes_Start']=Master['TS'].dt.minute

In [13]:
Master['Length']= Master['TS'].shift(-1) - Master['TS']
Master['TS End']= Master['TS'].shift(-1)
Master['Hour_End']= Master['TS End'].dt.hour
Master['Minutes_End']= Master['TS End'].dt.minute

In [14]:
##############################################################################
#pd.options.display.max_rows
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

# Fixing the last row

In [15]:
Master.iloc[-1, 7]= '2021-09-30 23:59:59.27'

In [16]:
Master['TS End']= pd.to_datetime(Master['TS End'], format = '%Y-%m-%d %H:%M:%S')

In [17]:
Master.iloc[-1,6]= Master.iloc[-1,7]- Master.iloc[-1,0]

In [18]:
Master.iloc[-1,8]= 23
Master.iloc[-1,9]= 59

In [19]:
Master['Hour_End']= Master['Hour_End'].astype(int)

# Adding middle hours

In [20]:
#When Lenght crosses 3 hours
Master.loc[Master['Hour_End']== Master['Hour_Start']+2 , 'Middle_1_Hour'] = Master['Hour_Start']+1
#exeptions
Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==0), 'Middle_1_Hour'] = 23

Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==1), 'Middle_1_Hour'] = 0


#When Legth crosses 4 hours
Master.loc[Master['Hour_End']== Master['Hour_Start']+3, 'Middle_2_Hour'] = Master['Hour_Start']+2
Master.loc[Master['Hour_End']== Master['Hour_Start']+3, 'Middle_1_Hour'] = Master['Hour_Start']+1
#exeptions
Master.loc[(Master['Hour_Start']== 21) & (Master['Hour_End']==0), 'Middle_2_Hour']=23
Master.loc[(Master['Hour_Start']== 21) & (Master['Hour_End']==0), 'Middle_1_Hour']=22

Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==1), 'Middle_2_Hour']=0
Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==1), 'Middle_1_Hour']=23

Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==2), 'Middle_2_Hour']=1
Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==2), 'Middle_1_Hour']=0


#when Length crosses 5 hours (ex. 3hr15min film starts at 6:50 ends at 10:05, thats 6,7,8,9,10)
Master.loc[Master['Hour_End']== Master['Hour_Start']+4, 'Middle_3_Hour'] = Master['Hour_Start']+3
Master.loc[Master['Hour_End']== Master['Hour_Start']+4, 'Middle_2_Hour'] = Master['Hour_Start']+2
Master.loc[Master['Hour_End']== Master['Hour_Start']+4, 'Middle_1_Hour'] = Master['Hour_Start']+1
#exeptions
Master.loc[(Master['Hour_Start']== 20) & (Master['Hour_End']==0), 'Middle_3_Hour']=23
Master.loc[(Master['Hour_Start']== 20) & (Master['Hour_End']==0), 'Middle_2_Hour']=22
Master.loc[(Master['Hour_Start']== 20) & (Master['Hour_End']==0), 'Middle_1_Hour']=21

Master.loc[(Master['Hour_Start']== 21) & (Master['Hour_End']==1), 'Middle_3_Hour']=0
Master.loc[(Master['Hour_Start']== 21) & (Master['Hour_End']==1), 'Middle_2_Hour']=23
Master.loc[(Master['Hour_Start']== 21) & (Master['Hour_End']==1), 'Middle_1_Hour']=22

Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==2), 'Middle_3_Hour']=1
Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==2), 'Middle_2_Hour']=0
Master.loc[(Master['Hour_Start']== 22) & (Master['Hour_End']==2), 'Middle_1_Hour']=23

Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==3), 'Middle_3_Hour']=2
Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==3), 'Middle_2_Hour']=1
Master.loc[(Master['Hour_Start']== 23) & (Master['Hour_End']==3), 'Middle_1_Hour']=0

# Adding the Percent of the total hour

In [21]:
#percentages
#First Hour
Master.loc[Master['Hour_Start']== (Master['Hour_End']),   'First'] = Master['Length']/timedelta(minutes=60)
Master.loc[Master['Hour_Start']+1 == Master['Hour_End'] , 'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[Master['Hour_Start']+2 == (Master['Hour_End']),'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[Master['Hour_Start']+3 == (Master['Hour_End']),'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[Master['Hour_Start']+4 == (Master['Hour_End']),'First'] = (60 -Master['TS'].dt.minute)/60


Master.loc[(Master['Hour_Start']== Master['Hour_End']+23),'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[(Master['Hour_Start']== Master['Hour_End']+22),'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[(Master['Hour_Start']== Master['Hour_End']+21),'First'] = (60 -Master['TS'].dt.minute)/60
Master.loc[(Master['Hour_Start']== Master['Hour_End']+20),'First'] = (60 -Master['TS'].dt.minute)/60


#Last Hour
Master.loc[Master['Hour_Start'] != Master['Hour_End'] ,   'Last'] = Master['Minutes_End']/60

#Mid Hours if necessarry
Master.loc[pd.notna(Master['Middle_1_Hour']),'Mid_1']=1
Master.loc[pd.notna(Master['Middle_2_Hour']),'Mid_2']=1
Master.loc[pd.notna(Master['Middle_3_Hour']),'Mid_3']=1

In [22]:
Master

,TS,Content ID,Title,Series/Film,Hour_Start,Minutes_Start,Length,TS End,Hour_End,Minutes_End,Middle_1_Hour,Middle_2_Hour,Middle_3_Hour,First,Last,Mid_1,Mid_2,Mid_3
0,2021-09-01 00:02:01.000,1000000000577,Maria!,Series,0,2,0 days 00:47:02.050000,2021-09-01 00:49:03.050,0,49.0,NaN,NaN,NaN,0.783903,NaN,NaN,NaN,NaN
1,2021-09-01 00:49:03.050,1000000000576,Maria!,Series,0,49,0 days 00:49:28.060000,2021-09-01 01:38:31.110,1,38.0,NaN,NaN,NaN,0.183333,0.633333,NaN,NaN,NaN
2,2021-09-01 01:38:31.110,1000000000748,The Chuey Martinez Show,Series,1,38,0 days 00:25:16.020000,2021-09-01 02:03:47.130,2,3.0,NaN,NaN,NaN,0.366667,0.050000,NaN,NaN,NaN
3,2021-09-01 02:03:47.130,CEG10031813,The Hills Have Eyes,Film,2,3,0 days 01:40:50.140000,2021-09-01 03:44:37.270,3,44.0,NaN,NaN,NaN,0.950000,0.733333,NaN,NaN,NaN
4,2021-09-01 03:44:37.270,CEG10031814,The Hills Have Eyes Part 2,Film,3,44,0 days 01:45:15.900000,2021-09-01 05:29:53.170,5,29.0,4.0,NaN,NaN,0.266667,0.483333,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810,2021-09-30 19:51:54.030,CEG10027418,Ip Man,Series,19,51,0 days 00:51:40.060000,2021-09-30 20:43:34.090,20,43.0,NaN,NaN,NaN,0.150000,0.716667,NaN,NaN,NaN
811,2021-09-30 20:43:34.090,CEG10027419,Ip Man,Series,20,43,0 days 00:51:06.970000,2021-09-30 21:34:41.060,21,34.0,NaN,NaN,NaN,0.283333,0.566667,NaN,NaN,NaN
812,2021-09-30 21:34:41.060,CEG10027420,Ip Man,Series,21,34,0 days 00:51:23.230000,2021-09-30 22:26:04.290,22,26.0,NaN,NaN,NaN,0.433333,0.433333,NaN,NaN,NaN
813,2021-09-30 22:26:04.290,CEG10026659,Ip Man,Series,22,26,0 days 00:49:22.730000,2021-09-30 23:15:27.020,23,15.0,NaN,NaN,NaN,0.566667,0.250000,NaN,NaN,NaN
814,2021-09-30 23:15:27.020,1000000000597,Maria!,Series,23,15,0 days 00:44:32.250000,2021-09-30 23:59:59.270,23,59.0,NaN,NaN,NaN,0.742292,NaN,NaN,NaN,NaN

# Merge Amagi with Glossary

In [23]:
Amagi.rename(columns={'Channel Name':'Platform/Channel'}, inplace= True)
Amagi= pd.merge(Amagi, glossary_channel, on= 'Platform/Channel', how='left')

#  Change to desired Channel

In [24]:
#Change Channel Name **************************************************************************************
Amagi=Amagi[Amagi['Channel']=='ElRey']

In [25]:
Amagi['Date']= pd.to_datetime(Amagi['Date'], format = '%m/%d/%Y %H:%M')

In [26]:
Amagi['Hour']= Amagi['Date'].dt.hour
Amagi['Day']= Amagi['Date'].dt.day

In [27]:
Amagi_Min=Amagi.groupby(['Day','Hour'])['Total Viewership Minutes'].agg(sum).reset_index()
Amagi_Sess=Amagi.groupby(['Day','Hour'])['Session Count'].agg(sum).reset_index()
Amagi_Min.rename(columns={'Total Viewership Minutes':'Min'}, inplace=True)
Amagi_Sess.rename(columns={'Session Count':'Sess'}, inplace=True)

In [28]:
Master['Day']= Master['TS'].dt.day

# Merging Master with Amagi Data

In [29]:
Master= pd.merge(Master, Amagi_Min ,left_on=['Day','Hour_Start'], right_on=['Day', 'Hour'], how='left' )
Master= pd.merge(Master, Amagi_Sess ,left_on=['Day','Hour_Start'], right_on=['Day', 'Hour'], how='left' )

In [30]:
Master.drop(columns=['Hour_x','Hour_y'], inplace= True)
Master.rename(columns={'Min':'Min_Hour_start'}, inplace=True)
Master.rename(columns={'Sess':'Sess_Hour_start'}, inplace= True)

In [31]:
Master= pd.merge(Master, Amagi_Min ,left_on=['Day','Middle_1_Hour'], right_on=['Day', 'Hour'], how='left' )
Master= pd.merge(Master, Amagi_Sess ,left_on=['Day','Middle_1_Hour'], right_on=['Day', 'Hour'], how='left' )

In [32]:
Master.drop(columns=['Hour_x','Hour_y'], inplace= True)
Master.rename(columns={'Min':'Min_Hour_Mid1'}, inplace=True)
Master.rename(columns={'Sess':'Sess_Hour_Mid1'}, inplace= True)

In [33]:
Master= pd.merge(Master, Amagi_Min ,left_on=['Day','Middle_2_Hour'], right_on=['Day', 'Hour'], how='left' )
Master= pd.merge(Master, Amagi_Sess ,left_on=['Day','Middle_2_Hour'], right_on=['Day', 'Hour'], how='left' )

In [34]:
Master.drop(columns=['Hour_x','Hour_y'], inplace= True)
Master.rename(columns={'Min':'Min_Hour_Mid2'}, inplace=True)
Master.rename(columns={'Sess':'Sess_Hour_Mid2'}, inplace= True)

In [35]:
Master= pd.merge(Master, Amagi_Min ,left_on=['Day','Middle_3_Hour'], right_on=['Day', 'Hour'], how='left' )
Master= pd.merge(Master, Amagi_Sess ,left_on=['Day','Middle_3_Hour'], right_on=['Day', 'Hour'], how='left' )

In [36]:
Master.drop(columns=['Hour_x','Hour_y'], inplace= True)
Master.rename(columns={'Min':'Min_Hour_Mid3'}, inplace=True)
Master.rename(columns={'Sess':'Sess_Hour_Mid3'}, inplace= True)

In [37]:
Master= pd.merge(Master, Amagi_Min ,left_on=['Day','Hour_End'], right_on=['Day', 'Hour'], how='left' )
Master= pd.merge(Master, Amagi_Sess ,left_on=['Day','Hour_End'], right_on=['Day', 'Hour'], how='left' )

In [38]:
Master.drop(columns=['Hour_x','Hour_y'], inplace= True)
Master.rename(columns={'Min':'Min_Hour_End'}, inplace=True)
Master.rename(columns={'Sess':'Sess_Hour_End'}, inplace= True)

In [39]:
Master.loc[(Master['Hour_Start']== Master['Hour_End']), 'Min_Hour_End']= 0

In [40]:
Master.loc[(Master['Hour_Start']== Master['Hour_End']), 'Sess_Hour_End']= 0

# Fill nan with 0

In [41]:
Master['Last']= Master['Last'].fillna(0)
Master['Mid_1']= Master['Mid_1'].fillna(0)
Master['Mid_2']= Master['Mid_2'].fillna(0)
Master['Mid_3']= Master['Mid_3'].fillna(0)

Master['Min_Hour_Mid1']= Master['Min_Hour_Mid1'].fillna(0)
Master['Min_Hour_Mid2']= Master['Min_Hour_Mid2'].fillna(0)
Master['Min_Hour_Mid3']= Master['Min_Hour_Mid3'].fillna(0)
Master['Min_Hour_End']= Master['Min_Hour_End'].fillna(0)

Master['Sess_Hour_Mid1']= Master['Sess_Hour_Mid1'].fillna(0)
Master['Sess_Hour_Mid2']= Master['Sess_Hour_Mid2'].fillna(0)
Master['Sess_Hour_Mid3']= Master['Sess_Hour_Mid3'].fillna(0)
Master['Sess_Hour_End']= Master['Sess_Hour_End'].fillna(0)

# Multiply percent of hour with data for whole hour

In [42]:
Master['Total Minutes']= ((Master['First']*Master['Min_Hour_start']) + 
(Master['Mid_1']*Master['Min_Hour_Mid1']) + 
(Master['Mid_2'] * Master['Min_Hour_Mid2']) + 
(Master['Mid_3'] * Master['Min_Hour_Mid3']) +                           
(Master['Last'] * Master['Min_Hour_End']))

Master['Total Session']= ((Master['First'] * Master['Sess_Hour_start']) + 
(Master['Mid_1'] * Master['Sess_Hour_Mid1']) + 
(Master['Mid_2'] * Master['Sess_Hour_Mid2']) + 
(Master['Mid_3'] * Master['Sess_Hour_Mid3']) + 
(Master['Last'] * Master['Sess_Hour_End']))

In [43]:
Master.drop(Master[Master['TS']==Master['TS End']].index, inplace=True)
Master.reset_index()
df= Master.loc[:,('Series/Film','Title','TS','Day','Hour_Start','Minutes_Start', 'Middle_1_Hour','Middle_2_Hour',
                  'Middle_3_Hour','Length','TS End',
                'Hour_End','Minutes_End','Total Minutes','Total Session')]

# Adding Daypart labels

In [44]:
df['Weekday']= df['TS'].dt.weekday

In [45]:
Conditions2 =[
    (df['Weekday'] < 5) & (df['Hour_Start'] < 6) & (df['Hour_Start'] >= 3),
    (df['Weekday'] < 5) & (df['Hour_Start'] < 13) & (df['Hour_Start'] >= 6),
    (df['Weekday'] < 5) & (df['Hour_Start'] < 17) & (df['Hour_Start'] >= 13),
    (df['Weekday'] < 5) & (df['Hour_Start'] < 20) & (df['Hour_Start'] >= 17),
    (df['Weekday'] < 5) & (df['Hour_Start'] < 23) & (df['Hour_Start'] >= 20),
    (df['Weekday'] < 5) & ((df['Hour_Start'] < 3) | (df['Hour_Start'] >= 23)),
    (df['Weekday'] >= 5) & (df['Hour_Start'] < 7) & (df['Hour_Start'] >= 3),
    (df['Weekday'] >= 5) & (df['Hour_Start'] < 17) & (df['Hour_Start'] >= 7),
    (df['Weekday'] >= 5) & (df['Hour_Start'] < 20) & (df['Hour_Start'] >= 17),
    (df['Weekday'] >= 5) & (df['Hour_Start'] < 23) & (df['Hour_Start'] >= 20),
    (df['Weekday'] >= 5) & ((df['Hour_Start'] < 3) | (df['Hour_Start'] >= 23)),
    
]

Daypart2 = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

df['Dayparts_Start']= np.select(Conditions2, Daypart2, default= np.nan)

In [46]:
Conditions3 =[
    (df['Weekday'] < 5) & (df['Hour_End'] < 6) & (df['Hour_End'] >= 3),
    (df['Weekday'] < 5) & (df['Hour_End'] < 13) & (df['Hour_End'] >= 6),
    (df['Weekday'] < 5) & (df['Hour_End'] < 17) & (df['Hour_End'] >= 13),
    (df['Weekday'] < 5) & (df['Hour_End'] < 20) & (df['Hour_End'] >= 17),
    (df['Weekday'] < 5) & (df['Hour_End'] < 23) & (df['Hour_End'] >= 20),
    (df['Weekday'] < 5) & ((df['Hour_End'] < 3) | (df['Hour_End'] >= 23)),
    (df['Weekday'] >= 5) & (df['Hour_End'] < 7) & (df['Hour_End'] >= 3),
    (df['Weekday'] >= 5) & (df['Hour_End'] < 17) & (df['Hour_End'] >= 7),
    (df['Weekday'] >= 5) & (df['Hour_End'] < 20) & (df['Hour_End'] >= 17),
    (df['Weekday'] >= 5) & (df['Hour_End'] < 23) & (df['Hour_End'] >= 20),
    (df['Weekday'] >= 5) & ((df['Hour_End'] < 3) | (df['Hour_End'] >= 23)),
    
]

Daypart3 = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

df['Dayparts_End']= np.select(Conditions3, Daypart3, default= np.nan)

In [47]:
df['com']= df['Dayparts_Start']+df['Dayparts_End']

In [48]:
dayp={ 'com':
['Weekday MorningWeekday Day' ,'Weekday DayWeekday Fringe','Weekday FringePrime'
,'PrimeLate Night','Late NightOvernight','OvernightWeekday Morning'
,'OvernightWeekend Morning','Weekend MorningWeekend Day','Weekend DayPrime (wknd)'
,'Prime (wknd)Late Night (wknd)','Late Night (wknd)Overnight (wknd)','Overnight (wknd)Weekend Morning'
,'Overnight (wknd)Weekday Morning'], 
      'DP_HR_Cross':
[6,13,17,20,23,3,3,7,17,20,23,3,3]
     }
daypp= pd.DataFrame(dayp, columns= ['com','DP_HR_Cross'])

In [49]:
df= pd.merge(df, daypp, on='com', how='left')

In [50]:
df['H']=pd.to_timedelta(df.DP_HR_Cross, unit='h')

In [51]:
df['date']= df['TS'].dt.date

In [52]:
df['date']= pd.to_datetime(df['date'])

In [53]:
df['DT_Cross']= df['date']+ df['H']

In [54]:
df['DP_ratio']= (df['DT_Cross']- df['TS'])/ df['Length']
df['DP2_ratio']=(df['TS End']- df['DT_Cross'])/ df['Length']

In [55]:
df.loc[df['DP_ratio']<= .1, 'DP_ratio']=0
df.loc[df['DP_ratio']>= .9, 'DP_ratio']=1
df.loc[df['DP_ratio']<= .1, 'DP2_ratio']=1
df.loc[df['DP_ratio']>= .9, 'DP2_ratio']=0

In [56]:
df['DP_ratio']= df['DP_ratio'].fillna(1)
df['DP2_ratio']= df['DP2_ratio'].fillna(0)

In [57]:
df['Min_total']= df['Total Minutes']
df['Sess_total']= df['Total Session']

In [58]:
df['Min_Daypart']= df['DP_ratio'] * df['Min_total']
df['Min_Daypart2']= df['DP2_ratio']* df['Min_total']

df['Sess_Daypart']=df['DP_ratio']* df['Sess_total']
df['Sess_Daypart2']=df['DP2_ratio']* df['Sess_total']

In [59]:
df['Sess_Duration'] = df['Min_Daypart']/ df['Sess_Daypart']
df['Sess_Duration2'] = df['Min_Daypart2']/ df['Sess_Daypart2']

In [60]:
df['Length_minutes']= df['Length']/timedelta(minutes=1)

In [61]:
df['Length_minutes_DP1']= df['Length_minutes']* df['DP_ratio']
df['Length_minutes_DP2']= df['Length_minutes']* df['DP2_ratio']

In [62]:
df['Minutes per min']= df['Min_Daypart']/df['Length_minutes_DP1']
df['Minutes_Second Daypart']= df['Min_Daypart2']/df['Length_minutes_DP2']

df['Sess per min']= df['Sess_Daypart']/df['Length_minutes_DP1']
df['Sess per min_Second Daypart']= df['Sess_Daypart2']/df['Length_minutes_DP2']

# Create Daypart Averages

In [63]:
Amagi_dp6.rename(columns={'Platform/Channel':'Channel Name'}, inplace=True)

In [64]:
Amagi_DP= pd.concat([Amagi_dp1, Amagi_dp2, Amagi_dp3, Amagi_dp4, Amagi_dp5], axis=0)
Amagi_DP['Date']= pd.to_datetime(Amagi_DP['Date'], format = '%m-%d-%Y %H:%M:%S')
Amagi_dp6['Date']= pd.to_datetime(Amagi_dp6['Date'], format = '%m/%d/%Y %H:%M')

In [65]:
Amagi_DP=pd.concat([Amagi_DP,Amagi_dp6], axis=0,ignore_index=True)

In [66]:
Amagi_DP.rename(columns={'Channel Name':'Platform/Channel'}, inplace= True)
Amagi_DP= pd.merge(Amagi_DP, glossary_channel, on= 'Platform/Channel', how='left')

#Change Channel Name*********************************************************************************
Amagi_DP=Amagi_DP[Amagi_DP['Channel']=='ElRey']

In [67]:
Amagi_DP['Weekday']= Amagi_DP['Date'].dt.weekday
Amagi_DP['Hour']= Amagi_DP['Date'].dt.hour
Amagi_DP['Day']= Amagi_DP['Date'].dt.day
Amagi_DP['Month']= Amagi_DP['Date'].dt.month

In [68]:
ADP= Amagi_DP

In [69]:
Conditions =[
    (ADP['Weekday'] < 5) & (ADP['Hour'] < 6) & (ADP['Hour'] >= 3),
    (ADP['Weekday'] < 5) & (ADP['Hour'] < 13) & (ADP['Hour'] >= 6),
    (ADP['Weekday'] < 5) & (ADP['Hour'] < 17) & (ADP['Hour'] >= 13),
    (ADP['Weekday'] < 5) & (ADP['Hour'] < 20) & (ADP['Hour'] >= 17),
    (ADP['Weekday'] < 5) & (ADP['Hour'] < 23) & (ADP['Hour'] >= 20),
    (ADP['Weekday'] < 5) & ((ADP['Hour'] < 3) | (ADP['Hour'] >= 23)),
    (ADP['Weekday'] >= 5) & (ADP['Hour'] < 7) & (ADP['Hour'] >= 3),
    (ADP['Weekday'] >= 5) & (ADP['Hour'] < 17) & (ADP['Hour'] >= 7),
    (ADP['Weekday'] >= 5) & (ADP['Hour'] < 20) & (ADP['Hour'] >= 17),
    (ADP['Weekday'] >= 5) & (ADP['Hour'] < 23) & (ADP['Hour'] >= 20),
    (ADP['Weekday'] >= 5) & ((ADP['Hour'] < 3) | (ADP['Hour'] >= 23)),
    
]

Daypart = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

ADP['Daypart']= np.select(Conditions, Daypart, default= np.nan)

In [70]:
ADP= ADP.groupby(['Month','Day','Hour','Daypart']).agg(sum).reset_index()

In [71]:
ADP=ADP.groupby(['Month','Daypart']).mean().reset_index()
ADP['Sess_Duration']= ADP['Total Viewership Minutes']/ ADP['Session Count']

In [72]:
ADPM= ADP.loc[:,('Month','Daypart', 'Total Viewership Minutes')]
ADPS= ADP.loc[:,('Month','Daypart', 'Sess_Duration')]

In [73]:
ADPM=ADPM.pivot( index= ['Daypart'], columns= 'Month')
ADPS=ADPS.pivot( index= ['Daypart'], columns= 'Month')

In [74]:
ADPM.columns= ADPM.columns.droplevel(0)
ADPM.columns.name= None
ADPM=ADPM.reset_index()

ADPS.columns= ADPS.columns.droplevel(0)
ADPS.columns.name=None
ADPS = ADPS.reset_index()

In [75]:
#ADPM[4]=ADPM[4]/60
#ADPM[5]=ADPM[5]/60
#ADPM[6]=ADPM[6]/60
#ADPM[7]=ADPM[7]/60
ADPM[8]=ADPM[8]/60
ADPM[9]=ADPM[9]/60

#ADPM['Q2']= (ADPM[4]+ ADPM[5]+ ADPM[6])/3
#ADPS['Q2']= (ADPS[4]+ ADPS[5]+ ADPS[6])/3

# Create Hourly Trends

In [76]:
Conditions =[
    (Amagi_DP['Weekday'] < 5) & (Amagi_DP['Hour'] < 6) & (Amagi_DP['Hour'] >= 3),
    (Amagi_DP['Weekday'] < 5) & (Amagi_DP['Hour'] < 13) & (Amagi_DP['Hour'] >= 6),
    (Amagi_DP['Weekday'] < 5) & (Amagi_DP['Hour'] < 17) & (Amagi_DP['Hour'] >= 13),
    (Amagi_DP['Weekday'] < 5) & (Amagi_DP['Hour'] < 20) & (Amagi_DP['Hour'] >= 17),
    (Amagi_DP['Weekday'] < 5) & (Amagi_DP['Hour'] < 23) & (Amagi_DP['Hour'] >= 20),
    (Amagi_DP['Weekday'] < 5) & ((Amagi_DP['Hour'] < 3) | (Amagi_DP['Hour'] >= 23)),
    (Amagi_DP['Weekday'] >= 5) & (Amagi_DP['Hour'] < 7) & (Amagi_DP['Hour'] >= 3),
    (Amagi_DP['Weekday'] >= 5) & (Amagi_DP['Hour'] < 17) & (Amagi_DP['Hour'] >= 7),
    (Amagi_DP['Weekday'] >= 5) & (Amagi_DP['Hour'] < 20) & (Amagi_DP['Hour'] >= 17),
    (Amagi_DP['Weekday'] >= 5) & (Amagi_DP['Hour'] < 23) & (Amagi_DP['Hour'] >= 20),
    (Amagi_DP['Weekday'] >= 5) & ((Amagi_DP['Hour'] < 3) | (Amagi_DP['Hour'] >= 23)),
    
]

Daypart = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

Amagi_DP['Daypart']= np.select(Conditions, Daypart, default= np.nan)

In [77]:
Amagi_DP= Amagi_DP.groupby(['Month','Day','Hour','Daypart']).agg(sum).reset_index()

In [78]:
Amagi_DP['Month']=Amagi_DP['Month'].astype('category')
Amagi_DP['Day']=Amagi_DP['Day'].astype('category')
Amagi_DP['Hour']=Amagi_DP['Hour'].astype('category')

In [79]:
Amagi_DP=Amagi_DP.groupby(['Month','Day','Hour','Daypart']).mean().reset_index()
Amagi_DP['Sess_Duration']= Amagi_DP['Total Viewership Minutes']/ Amagi_DP['Session Count']

In [80]:
Amagi_DP= Amagi_DP.loc[:,('Month','Day','Hour','Daypart','Total Viewership Minutes','Sess_Duration')]

In [81]:
Amagi_DP['Total Viewership Minutes per minute']=Amagi_DP['Total Viewership Minutes']/60

In [82]:
Amagi_DP=Amagi_DP[Amagi_DP['Sess_Duration'].notna()]

In [83]:
Conditions=[
(Amagi_DP['Daypart'] == 'Weekday Morning') | (Amagi_DP['Daypart']=='Weekday Day') | (Amagi_DP['Daypart']=='Weekday Fringe') | (Amagi_DP['Daypart']=='Prime') | (Amagi_DP['Daypart']=='Late Night') | (Amagi_DP['Daypart']=='Overnight'),
(Amagi_DP['Daypart']== 'Weekend Morning') | (Amagi_DP['Daypart']=='Weekend Day') | (Amagi_DP['Daypart']=='Prime (wknd)') | (Amagi_DP['Daypart']=='Late Night (wknd)') | (Amagi_DP['Daypart']=='Overnight (wknd)')    
]

results= ['Weekday', 'Weekend']

Amagi_DP['week/weekend']= np.select(Conditions, results, default=np.nan)

# Daypart Averages Table

In [84]:
Amagi_DP_weekdays= Amagi_DP[Amagi_DP['week/weekend']== 'Weekday']
Amagi_DP_weekends= Amagi_DP[Amagi_DP['week/weekend']== 'Weekend']

In [85]:
Amagi_DP_weekdays=Amagi_DP_weekdays.groupby(['Month','Hour','Daypart']).mean().reset_index()
Amagi_DP_weekends=Amagi_DP_weekends.groupby(['Month','Hour','Daypart']).mean().reset_index()

Amagi_DP_weekdays.dropna(inplace=True)
Amagi_DP_weekends.dropna(inplace=True)

In [86]:
ADPw=Amagi_DP_weekdays.pivot(index=['Hour'],columns='Month',values=['Total Viewership Minutes',
                                                                    'Sess_Duration']).swaplevel(0,1,axis=1).reset_index()
ADPwk=Amagi_DP_weekends.pivot(index=['Hour'],columns='Month',values=['Total Viewership Minutes',
                                                                    'Sess_Duration']).swaplevel(0,1,axis=1).reset_index()

In [87]:
ADPw.columns= ADPw.columns.droplevel(1)
ADPwk.columns= ADPwk.columns.droplevel(1)

In [88]:
ADPw.rename(columns={4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep','Hour':'Hour(24-Pac)'},inplace=True)
ADPwk.rename(columns={4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep','Hour':'Hour(24-Pac)'},inplace=True)

In [89]:
Con5=[
    (ADPw['Hour(24-Pac)']== 0),(ADPw['Hour(24-Pac)']== 1),(ADPw['Hour(24-Pac)']== 2),(ADPw['Hour(24-Pac)']== 3),
    (ADPw['Hour(24-Pac)']== 4),(ADPw['Hour(24-Pac)']== 5),(ADPw['Hour(24-Pac)']== 6),(ADPw['Hour(24-Pac)']== 7),
    (ADPw['Hour(24-Pac)']== 8),(ADPw['Hour(24-Pac)']== 9),(ADPw['Hour(24-Pac)']== 10),(ADPw['Hour(24-Pac)']== 11),
    (ADPw['Hour(24-Pac)']== 12),(ADPw['Hour(24-Pac)']== 13),(ADPw['Hour(24-Pac)']== 14),(ADPw['Hour(24-Pac)']== 15),
    (ADPw['Hour(24-Pac)']== 16),(ADPw['Hour(24-Pac)']== 17),(ADPw['Hour(24-Pac)']== 18),(ADPw['Hour(24-Pac)']== 19),
    (ADPw['Hour(24-Pac)']== 20),(ADPw['Hour(24-Pac)']== 21),(ADPw['Hour(24-Pac)']== 22),(ADPw['Hour(24-Pac)']== 23),  
]

Con6=[
    (ADPwk['Hour(24-Pac)']== 0),(ADPwk['Hour(24-Pac)']== 1),(ADPwk['Hour(24-Pac)']== 2),(ADPwk['Hour(24-Pac)']== 3),
    (ADPwk['Hour(24-Pac)']== 4),(ADPwk['Hour(24-Pac)']== 5),(ADPwk['Hour(24-Pac)']== 6),(ADPwk['Hour(24-Pac)']== 7),
    (ADPwk['Hour(24-Pac)']== 8),(ADPwk['Hour(24-Pac)']== 9),(ADPwk['Hour(24-Pac)']== 10),(ADPwk['Hour(24-Pac)']== 11),
    (ADPwk['Hour(24-Pac)']== 12),(ADPwk['Hour(24-Pac)']== 13),(ADPwk['Hour(24-Pac)']== 14),(ADPwk['Hour(24-Pac)']== 15),
    (ADPwk['Hour(24-Pac)']== 16),(ADPwk['Hour(24-Pac)']== 17),(ADPwk['Hour(24-Pac)']== 18),(ADPwk['Hour(24-Pac)']== 19),
    (ADPwk['Hour(24-Pac)']== 20),(ADPwk['Hour(24-Pac)']== 21),(ADPwk['Hour(24-Pac)']== 22),(ADPwk['Hour(24-Pac)']== 23),  
]




pac=['0am-pt','1am-pt','2am-pt','3am-pt','4am-pt','5am-pt',
    '6am-pt','7am-pt','8am-pt','9am-pt','10am-pt','11am-pt',
    '12pm-pt','1pm-pt','2pm-pt','3pm-pt','4pm-pt','5pm-pt',
    '6pm-pt','7pm-pt','8pm-pt','9pm-pt','10pm-pt','11pm-pt',]

east=['3am-et','4am-et','5am-et','6am-et','7am-et','8am-et',
      '9am-et','10am-et','11am-et','12pm-et','1pm-et','2pm-et',
      '3pm-et','4pm-et','5pm-et','6pm-et','7pm-et','8pm-et',
      '9pm-et','10pm-et','11pm-et','0am-et','1am-et','2am-et']

ADPw['Pacific_Time']=np.select(Con5,pac,default=np.nan)
ADPw['East_Time']=np.select(Con5,east,default=np.nan)

ADPwk['Pacific_Time']=np.select(Con6,pac,default=np.nan)
ADPwk['East_Time']=np.select(Con6,east,default=np.nan)

In [90]:
Amagi_DPA= ADPw.append(ADPwk)

# Merge Daypart Averages df

In [91]:
dfmin=pd.merge(df,ADPM, left_on='Dayparts_Start', right_on='Daypart', how='left')
dfmin=pd.merge(dfmin,ADPM, left_on='Dayparts_End', right_on='Daypart', how='left')

In [92]:
dfsessD=pd.merge(df,ADPS, left_on='Dayparts_Start', right_on='Daypart', how='left')
dfsessD=pd.merge(dfsessD,ADPS, left_on='Dayparts_End', right_on='Daypart', how='left')

In [93]:
#dfmin['Performance - Q2(Daypart avg)']= (dfmin['Minutes per min']- dfmin['Q2_x'])/dfmin['Q2_x']
#dfmin['Performance - July(Daypart avg)']= (dfmin['Minutes per min']- dfmin['7_x'])/dfmin['7_x']
dfmin['Performance - August(Daypart avg)']= (dfmin['Minutes per min']- dfmin['8_x'])/dfmin['8_x']
dfmin['Performance - September(Daypart avg)']= (dfmin['Minutes per min']- dfmin['9_x'])/dfmin['9_x']


#dfmin['Performance2 - Q2(Daypart avg)']= (dfmin['Minutes_Second Daypart']- dfmin['Q2_y'])/dfmin['Q2_y']
#dfmin['Performance2 - July(Daypart avg)']= (dfmin['Minutes_Second Daypart']- dfmin['7_y'])/dfmin['7_y']
dfmin['Performance2 - August(Daypart avg)']= (dfmin['Minutes_Second Daypart']- dfmin['8_y'])/dfmin['8_y']
dfmin['Performance2 - September(Daypart avg)']= (dfmin['Minutes_Second Daypart']- dfmin['9_y'])/dfmin['9_y']

In [94]:
#dfsessD['Performance - Q2(Daypart avg)']= (dfsessD['Sess_Duration']- dfsessD['Q2_x'])/dfsessD['Q2_x']
#dfsessD['Performance - July(Daypart avg)']= (dfsessD['Sess_Duration']- dfsessD['7_x'])/dfsessD['7_x']
dfsessD['Performance - August(Daypart avg)']= (dfsessD['Sess_Duration']- dfsessD['8_x'])/dfsessD['8_x']
dfsessD['Performance - September(Daypart avg)']= (dfsessD['Sess_Duration']- dfsessD['9_x'])/dfsessD['9_x']


#dfsessD['Performance2 - Q2(Daypart avg)']= (dfsessD['Sess_Duration2']- dfsessD['Q2_y'])/dfsessD['Q2_y']
#dfsessD['Performance2 - July(Daypart avg)']= (dfsessD['Sess_Duration2']- dfsessD['7_y'])/dfsessD['7_y']
dfsessD['Performance2 - August(Daypart avg)']= (dfsessD['Sess_Duration2']- dfsessD['8_y'])/dfsessD['8_y']
dfsessD['Performance2 - September(Daypart avg)']= (dfsessD['Sess_Duration2']- dfsessD['9_y'])/dfsessD['9_y']

In [95]:
dfmin=dfmin.loc[:,('Series/Film','Length_minutes', 'Title', 'Dayparts_Start', 'Length_minutes_DP1',
                   'Performance - August(Daypart avg)','Performance - September(Daypart avg)','Dayparts_End',
                    'Length_minutes_DP2', 
                   'Performance2 - August(Daypart avg)', 'Performance2 - September(Daypart avg)',
                   'TS','Minutes per min', 'Minutes_Second Daypart')]

In [96]:
dfsessD=dfsessD.loc[:,('Series/Film','Length_minutes', 'Title', 'Dayparts_Start', 'Length_minutes_DP1',
                    'Performance - August(Daypart avg)', 'Performance - September(Daypart avg)' ,'Dayparts_End',
                    'Length_minutes_DP2', 
                    'Performance2 - August(Daypart avg)', 'Performance2 - September(Daypart avg)' ,
                    'TS','Sess_Duration','Sess_Duration2')]

In [97]:
dfsessD['Session Duration']= dfsessD[['Sess_Duration','Sess_Duration2']].mean(axis=1)
dfmin['Minutes per min (avg)']= dfmin[['Minutes per min','Minutes_Second Daypart']].mean(axis=1)

# Master/DF hourly Breakdown

In [98]:
Master['First_Hour_Min']=Master['First']*Master['Min_Hour_start']
Master['Second_Hour_Min']=Master['Mid_1']*Master['Min_Hour_Mid1']
Master['Third_Hour_Min']=Master['Mid_2']*Master['Min_Hour_Mid2']
Master['Fourth_Hour_Min']=Master['Mid_3']*Master['Min_Hour_Mid3']
Master['Last_Hour_Min']=Master['Last']*Master['Min_Hour_End']

Master['First_Hour_Sess']=Master['First']*Master['Sess_Hour_start']
Master['Second_Hour_Sess']=Master['Mid_1']*Master['Sess_Hour_Mid1']
Master['Third_Hour_Sess']=Master['Mid_2']*Master['Sess_Hour_Mid2']
Master['Fourth_Hour_Sess']=Master['Mid_3']*Master['Sess_Hour_Mid3']
Master['Last_Hour_Sess']=Master['Last']*Master['Sess_Hour_End']

In [99]:
Master['Length_1']=Master['First']*60
Master['Length_2']=Master['Mid_1']*60
Master['Length_3']=Master['Mid_2']*60
Master['Length_4']=Master['Mid_3']*60
Master['Length_5']=Master['Last']*60

In [100]:
Master1= Master.loc[:,('Content ID','TS','TS End','Title','Series/Film','Hour_Start','First_Hour_Min','First_Hour_Sess',
                       'Length_1','Total Minutes','Total Session')]
Master2= Master.loc[:,('Content ID','TS','TS End','Title','Series/Film','Middle_1_Hour','Second_Hour_Min','Second_Hour_Sess',
                       'Length_2','Total Minutes','Total Session')]
Master3= Master.loc[:,('Content ID','TS','TS End','Title','Series/Film','Middle_2_Hour','Third_Hour_Min','Third_Hour_Sess',
                       'Length_3','Total Minutes','Total Session')]
Master4= Master.loc[:,('Content ID','TS','TS End','Title','Series/Film','Middle_3_Hour','Fourth_Hour_Min','Fourth_Hour_Sess',
                       'Length_4','Total Minutes','Total Session')]
Master5= Master.loc[:,('Content ID','TS','TS End','Title','Series/Film','Hour_End','Last_Hour_Min','Last_Hour_Sess',
                       'Length_5','Total Minutes','Total Session')]

In [101]:
Master1.rename(columns={'Hour_Start':'Hour','First_Hour_Min':'Minutes Viewed in Hour','Length_1':'Length(min) in the Hour',
                        'First_Hour_Sess':'Sessions in Hour'},inplace=True)
Master2.rename(columns={'Middle_1_Hour':'Hour','Second_Hour_Min':'Minutes Viewed in Hour','Length_2':'Length(min) in the Hour',
                        'Second_Hour_Sess':'Sessions in Hour'},inplace=True)
Master3.rename(columns={'Middle_2_Hour':'Hour','Third_Hour_Min':'Minutes Viewed in Hour','Length_3':'Length(min) in the Hour',
                        'Third_Hour_Sess':'Sessions in Hour'},inplace=True)
Master4.rename(columns={'Middle_3_Hour':'Hour','Fourth_Hour_Min':'Minutes Viewed in Hour','Length_4':'Length(min) in the Hour',
                        'Fourth_Hour_Sess':'Sessions in Hour'},inplace=True)
Master5.rename(columns={'Hour_End':'Hour','Last_Hour_Min':'Minutes Viewed in Hour','Length_5':'Length(min) in the Hour',
                        'Last_Hour_Sess':'Sessions in Hour'},inplace=True)

In [102]:
DF= Master1.append([Master2,Master3,Master4,Master5])
DF.dropna(inplace=True)
DF['Weekday']= DF['TS'].dt.weekday

In [103]:
Conditions1 =[
    (DF['Weekday'] < 5) & (DF['Hour'] < 6) & (DF['Hour'] >= 3),
    (DF['Weekday'] < 5) & (DF['Hour'] < 13) & (DF['Hour'] >= 6),
    (DF['Weekday'] < 5) & (DF['Hour'] < 17) & (DF['Hour'] >= 13),
    (DF['Weekday'] < 5) & (DF['Hour'] < 20) & (DF['Hour'] >= 17),
    (DF['Weekday'] < 5) & (DF['Hour'] < 23) & (DF['Hour'] >= 20),
    (DF['Weekday'] < 5) & ((DF['Hour'] < 3) | (DF['Hour'] >= 23)),
    (DF['Weekday'] >= 5) & (DF['Hour'] < 7) & (DF['Hour'] >= 3),
    (DF['Weekday'] >= 5) & (DF['Hour'] < 17) & (DF['Hour'] >= 7),
    (DF['Weekday'] >= 5) & (DF['Hour'] < 20) & (DF['Hour'] >= 17),
    (DF['Weekday'] >= 5) & (DF['Hour'] < 23) & (DF['Hour'] >= 20),
    (DF['Weekday'] >= 5) & ((DF['Hour'] < 3) | (DF['Hour'] >= 23)),
    
]

Daypart1 = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

DF['Daypart']= np.select(Conditions1, Daypart1, default= np.nan)

In [104]:
DF['Minutes per Minute']= DF['Minutes Viewed in Hour']/DF['Length(min) in the Hour']
DF['Sessions per Minute']= DF['Sessions in Hour']/DF['Length(min) in the Hour']
DF['Session Duration']= DF['Minutes Viewed in Hour']/DF['Sessions in Hour']
DF['Day']= DF['TS'].dt.day

# Month Breakdown

In [105]:
Condwk=[
    DF['Weekday']== 0,DF['Weekday']== 1,DF['Weekday']== 2,DF['Weekday']== 3,
    DF['Weekday']== 4,DF['Weekday']== 5,DF['Weekday']== 6   
]

wkdays= ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']

DF['Weekday(name)']= np.select(Condwk,wkdays, default=np.nan)

In [106]:
DF= DF.loc[:,('Content ID','TS','TS End','Length(min) in the Hour','Day','Weekday','Weekday(name)','Hour','Series/Film',
             'Title','Daypart','Minutes per Minute','Sessions per Minute','Session Duration')]

In [107]:
DF.dropna(inplace=True)
DF.sort_values(by=['TS','TS End'])
DF['Hour']=DF['Hour'].astype(int)
DF.rename(columns={'Hour':'Hour(24-Pac)','Weekday':'Weekday(num)','Weekday(name)':'Weekday'},inplace=True)

In [108]:
Con4=[
    (DF['Hour(24-Pac)']== 0),(DF['Hour(24-Pac)']== 1),(DF['Hour(24-Pac)']== 2),(DF['Hour(24-Pac)']== 3),
    (DF['Hour(24-Pac)']== 4),(DF['Hour(24-Pac)']== 5),(DF['Hour(24-Pac)']== 6),(DF['Hour(24-Pac)']== 7),
    (DF['Hour(24-Pac)']== 8),(DF['Hour(24-Pac)']== 9),(DF['Hour(24-Pac)']== 10),(DF['Hour(24-Pac)']== 11),
    (DF['Hour(24-Pac)']== 12),(DF['Hour(24-Pac)']== 13),(DF['Hour(24-Pac)']== 14),(DF['Hour(24-Pac)']== 15),
    (DF['Hour(24-Pac)']== 16),(DF['Hour(24-Pac)']== 17),(DF['Hour(24-Pac)']== 18),(DF['Hour(24-Pac)']== 19),
    (DF['Hour(24-Pac)']== 20),(DF['Hour(24-Pac)']== 21),(DF['Hour(24-Pac)']== 22),(DF['Hour(24-Pac)']== 23),
    
]

pac=['0am-pt','1am-pt','2am-pt','3am-pt','4am-pt','5am-pt',
    '6am-pt','7am-pt','8am-pt','9am-pt','10am-pt','11am-pt',
    '12pm-pt','1pm-pt','2pm-pt','3pm-pt','4pm-pt','5pm-pt',
    '6pm-pt','7pm-pt','8pm-pt','9pm-pt','10pm-pt','11pm-pt',]

east=['3am-et','4am-et','5am-et','6am-et','7am-et','8am-et',
      '9am-et','10am-et','11am-et','12pm-et','1pm-et','2pm-et',
      '3pm-et','4pm-et','5pm-et','6pm-et','7pm-et','8pm-et',
      '9pm-et','10pm-et','11pm-et','0am-et','1am-et','2am-et']

DF['Pacific_Time']=np.select(Con4,pac,default=np.nan)
DF['East_Time']=np.select(Con4,east,default=np.nan)

In [109]:
DF= DF.loc[:,('Content ID','TS','TS End','Length(min) in the Hour','Day','Weekday(num)','Weekday','Hour(24-Pac)','Pacific_Time',
              'East_Time','Series/Film','Title','Daypart','Minutes per Minute','Sessions per Minute','Session Duration')]

# Building Confidence Intervals

In [110]:
DF.sort_values(by=['TS','Hour(24-Pac)'], inplace=True)
DF=DF.reset_index()

In [111]:
DF.loc[(DF['TS'].dt.hour != DF['TS End'].dt.hour) & (DF['Hour(24-Pac)']==0),'Day'] = DF['TS End'].dt.day

In [112]:
DF.loc[(DF['TS'].dt.hour != DF['TS End'].dt.hour) & (DF['Hour(24-Pac)']==0),'Weekday(num)'] = DF['TS End'].dt.weekday

In [113]:
Condwk=[
    DF['Weekday(num)']== 0,DF['Weekday(num)']== 1,DF['Weekday(num)']== 2,DF['Weekday(num)']== 3,
    DF['Weekday(num)']== 4,DF['Weekday(num)']== 5,DF['Weekday(num)']== 6   
]

wkdays= ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']

DF['Weekday(name)']= np.select(Condwk,wkdays, default=np.nan)

In [114]:
Conditions1 =[
    (DF['Weekday(num)'] < 5) & (DF['Hour(24-Pac)'] < 6) & (DF['Hour(24-Pac)'] >= 3),
    (DF['Weekday(num)'] < 5) & (DF['Hour(24-Pac)'] < 13) & (DF['Hour(24-Pac)'] >= 6),
    (DF['Weekday(num)'] < 5) & (DF['Hour(24-Pac)'] < 17) & (DF['Hour(24-Pac)'] >= 13),
    (DF['Weekday(num)'] < 5) & (DF['Hour(24-Pac)'] < 20) & (DF['Hour(24-Pac)'] >= 17),
    (DF['Weekday(num)'] < 5) & (DF['Hour(24-Pac)'] < 23) & (DF['Hour(24-Pac)'] >= 20),
    (DF['Weekday(num)'] < 5) & ((DF['Hour(24-Pac)'] < 3) | (DF['Hour(24-Pac)'] >= 23)),
    (DF['Weekday(num)'] >= 5) & (DF['Hour(24-Pac)'] < 7) & (DF['Hour(24-Pac)'] >= 3),
    (DF['Weekday(num)'] >= 5) & (DF['Hour(24-Pac)'] < 17) & (DF['Hour(24-Pac)'] >= 7),
    (DF['Weekday(num)'] >= 5) & (DF['Hour(24-Pac)'] < 20) & (DF['Hour(24-Pac)'] >= 17),
    (DF['Weekday(num)'] >= 5) & (DF['Hour(24-Pac)'] < 23) & (DF['Hour(24-Pac)'] >= 20),
    (DF['Weekday(num)'] >= 5) & ((DF['Hour(24-Pac)'] < 3) | (DF['Hour(24-Pac)'] >= 23)),
    
]

Daypart1 = ['Weekday Morning','Weekday Day', 'Weekday Fringe','Prime', 'Late Night', 'Overnight',
           'Weekend Morning', 'Weekend Day', 'Prime (wknd)', 'Late Night (wknd)', 'Overnight (wknd)'
         ]

DF['Daypart1']= np.select(Conditions1, Daypart1, default= np.nan)

In [115]:
DF.rename(columns={'Daypart':'no','Daypart1':'Daypart'}, inplace=True)

In [116]:
DF=DF.loc[:,('Content ID','TS','TS End','Length(min) in the Hour','Day','Weekday(num)','Weekday(name)','Hour(24-Pac)',
            'Pacific_Time','East_Time','Series/Film','Title','Daypart','Minutes per Minute',
             'Sessions per Minute','Session Duration')]

In [117]:
Cond=[
    (DF['Weekday(num)']== 5) | (DF['Weekday(num)']==6),
    (DF['Weekday(num)']== 0)|(DF['Weekday(num)']==1)|(DF['Weekday(num)']== 2)|(DF['Weekday(num)']==3)|
    (DF['Weekday(num)']== 4)
]

Values=['Weekend','Weekday']

DF['Weekdays/Weekends']= np.select(Cond,Values)

In [118]:
HR=DF.groupby(['Weekdays/Weekends','Day','Hour(24-Pac)']).mean().reset_index()

In [119]:
Hourly_AVG= HR.loc[:,('Minutes per Minute','Weekdays/Weekends','Hour(24-Pac)')].groupby(['Weekdays/Weekends',
                                        'Hour(24-Pac)']).mean().reset_index()
Hourly_STD= HR.loc[:,('Minutes per Minute','Weekdays/Weekends','Hour(24-Pac)')].groupby(['Weekdays/Weekends',
                                        'Hour(24-Pac)']).std().reset_index()
Hourly_Count= HR.loc[:,('Minutes per Minute','Weekdays/Weekends','Hour(24-Pac)')].groupby(['Weekdays/Weekends',
                                        'Hour(24-Pac)']).count().reset_index()

In [120]:
Hourly_AVG.rename(columns={'Minutes per Minute':'Hourly AVG'},inplace=True)
Hourly_STD.rename(columns={'Minutes per Minute':'Hourly STD'},inplace=True)
Hourly_Count.rename(columns={'Minutes per Minute':'Hourly Count'},inplace=True)

In [121]:
DF= pd.merge(DF,Hourly_AVG, on=['Weekdays/Weekends','Hour(24-Pac)'], how='left')
DF= pd.merge(DF,Hourly_STD, on=['Weekdays/Weekends','Hour(24-Pac)'], how='left')
DF= pd.merge(DF,Hourly_Count, on=['Weekdays/Weekends','Hour(24-Pac)'], how='left')

In [122]:
DF.loc[DF['Weekdays/Weekends']=='Weekday', 
       'Wk/Wknd Upper CI(95%)']= DF['Hourly AVG']+(2.08* (DF['Hourly STD']/(DF['Hourly Count']**(1/2))))
DF.loc[DF['Weekdays/Weekends']=='Weekday',
       'Wk/Wknd Lower CI(95%)']= DF['Hourly AVG']-(2.08* (DF['Hourly STD']/(DF['Hourly Count']**(1/2))))

DF.loc[DF['Weekdays/Weekends']=='Weekend', 
       'Wk/Wknd Upper CI(95%)']= DF['Hourly AVG']+(2.447* (DF['Hourly STD']/(DF['Hourly Count']**(1/2))))
DF.loc[DF['Weekdays/Weekends']=='Weekend',
       'Wk/Wknd Lower CI(95%)']= DF['Hourly AVG']-(2.447* (DF['Hourly STD']/(DF['Hourly Count']**(1/2))))

# Summary CI

In [123]:
Con1=[
    (DF['Minutes per Minute'] > DF['Wk/Wknd Upper CI(95%)']),
    (DF['Minutes per Minute'] < DF['Wk/Wknd Lower CI(95%)']),
    (DF['Minutes per Minute'] <= DF['Wk/Wknd Upper CI(95%)']) & (DF['Minutes per Minute'] >= DF['Wk/Wknd Lower CI(95%)'])     
]

Values1= ['Above','Below','Neutral']

DF['Wk/Wknd Above/Below']=np.select(Con1,Values1, default=np.nan)

In [124]:
Con1=[
    (DF['Wk/Wknd Above/Below']== 'Above'), (DF['Wk/Wknd Above/Below']== 'Below'), (DF['Wk/Wknd Above/Below']== 'Neutral'),
]

Values1=[(DF['Minutes per Minute']-DF['Wk/Wknd Upper CI(95%)']),
         (DF['Minutes per Minute']-DF['Wk/Wknd Lower CI(95%)']),
         0]
DF['Above/Below (Dist)']= np.select(Con1,Values1, default=np.nan)

In [125]:
DF['Above/Below %']=(DF['Above/Below (Dist)']/DF['Hourly AVG'])

In [126]:
W=DF.loc[:,('Title','Series/Film','Wk/Wknd Above/Below','Content ID')]

In [127]:
W=W.pivot_table(index= ['Series/Film','Title'], values='Content ID', columns='Wk/Wknd Above/Below', aggfunc=pd.Series.count)

In [128]:
W=W.reset_index()

In [129]:
W['Above']=W['Above'].fillna(0)
W['Below']=W['Below'].fillna(0)
W['Neutral']=W['Neutral'].fillna(0)


W['Count']= (W['Above']+ W['Below']+ W['Neutral'])
W['%Below CI']= W['Below']/W['Count']
W['%Inside CI']= W['Neutral']/W['Count']
W['%Above CI']= W['Above']/W['Count']
W['Score']= ((W['Above']**2)-(W['Below']**2))/W['Count']

In [130]:
W1=DF.loc[:,('Title','Series/Film','Above/Below (Dist)','Above/Below %')]
W1= W1.groupby('Title').mean().reset_index()

In [131]:
SummaryW= pd.merge(W,W1, on='Title', how='left')

In [132]:
SummaryW= SummaryW.loc[:,('Series/Film','Title','Above','Neutral','Below','Count','%Above CI','%Inside CI',
                         '%Below CI','Score','Above/Below (Dist)','Above/Below %')]

# Counts in Dayparts

In [133]:
DF1= DF.loc[:,('Content ID','Title','Daypart','Wk/Wknd Above/Below')]

In [134]:
DF1=DF1.pivot_table(index='Title', columns=['Daypart','Wk/Wknd Above/Below'], values='Content ID', aggfunc=pd.Series.count)

In [135]:
DF1.reset_index(inplace=True)

In [136]:
DF1.columns=['Title',
             'LateNight ABOVE','LateNight BELOW','LateNight NEUTRAL',
             'LateNight(wknd) ABOVE','LateNight(wknd) BELOW','LateNight(wknd) NEUTRAL',
             'Overnight ABOVE','Overnight BELOW','Overnight NEUTRAL',
             'Overnight(wknd) ABOVE','Overnight(wknd) BELOW','Overnight(wknd) NEUTRAL',
             'Prime ABOVE','Prime BELOW','Prime NEUTRAL',
             'Prime(wknd) ABOVE','Prime(wknd) BELOW','Prime(wknd) NEUTRAL',
             'WeekdayDay ABOVE','WeekdayDay BELOW','WeekdayDay NEUTRAL',
             'WeekdayFringe ABOVE','WeekdayFringe BELOW','WeekdayFringe NEUTRAL',
             'WeekdayMorning ABOVE','WeekdayMorning BELOW','WeekdayMorning NEUTRAL',
             'WeekendDay ABOVE','WeekendDay BELOW','WeekendDay NEUTRAL',
             'WeekendMorning ABOVE','WeekendMorning BELOW','WeekendMorning NEUTRAL']

In [137]:
DF1=DF1.loc[:,('Title',
             'LateNight ABOVE','LateNight NEUTRAL','LateNight BELOW',
             'LateNight(wknd) ABOVE','LateNight(wknd) NEUTRAL','LateNight(wknd) BELOW',
             'Overnight ABOVE','Overnight NEUTRAL','Overnight BELOW',
             'Overnight(wknd) ABOVE','Overnight(wknd) NEUTRAL','Overnight(wknd) BELOW',
             'Prime ABOVE','Prime NEUTRAL','Prime BELOW',
             'Prime(wknd) ABOVE','Prime(wknd) NEUTRAL','Prime(wknd) BELOW',
             'WeekdayDay ABOVE','WeekdayDay NEUTRAL','WeekdayDay BELOW',
             'WeekdayFringe ABOVE','WeekdayFringe NEUTRAL','WeekdayFringe BELOW',
             'WeekdayMorning ABOVE','WeekdayMorning NEUTRAL','WeekdayMorning BELOW',
             'WeekendDay ABOVE','WeekendDay NEUTRAL','WeekendDay BELOW',
             'WeekendMorning ABOVE','WeekendMorning NEUTRAL','WeekendMorning BELOW')]

In [138]:
DF1=DF1.fillna(0)

In [139]:
DF1['LateNight Count']=DF1['LateNight ABOVE']+DF1['LateNight NEUTRAL']+DF1['LateNight BELOW']
DF1['LateNight(wknd) Count']=DF1['LateNight(wknd) ABOVE']+DF1['LateNight(wknd) NEUTRAL']+DF1['LateNight(wknd) BELOW']
DF1['Overnight Count']=DF1['Overnight ABOVE']+DF1['Overnight NEUTRAL']+DF1['Overnight BELOW']
DF1['Overnight(wknd) Count']=DF1['Overnight(wknd) ABOVE']+DF1['Overnight(wknd) NEUTRAL']+DF1['Overnight(wknd) BELOW']
DF1['Prime Count']=DF1['Prime ABOVE']+DF1['Prime NEUTRAL']+DF1['Prime BELOW']
DF1['Prime(wknd) Count']=DF1['Prime(wknd) ABOVE']+DF1['Prime(wknd) NEUTRAL']+DF1['Prime(wknd) BELOW']
DF1['WeekdayDay Count']=DF1['WeekdayDay ABOVE']+DF1['WeekdayDay NEUTRAL']+DF1['WeekdayDay BELOW']
DF1['WeekdayFringe Count']=DF1['WeekdayFringe ABOVE']+DF1['WeekdayFringe NEUTRAL']+DF1['WeekdayFringe BELOW']
DF1['WeekdayMorning Count']=DF1['WeekdayMorning ABOVE']+DF1['WeekdayMorning NEUTRAL']+DF1['WeekdayMorning BELOW']
DF1['WeekendDay Count']=DF1['WeekendDay ABOVE']+DF1['WeekendDay NEUTRAL']+DF1['WeekendDay BELOW']
DF1['WeekendMorning Count']=DF1['WeekendMorning ABOVE']+DF1['WeekendMorning NEUTRAL']+DF1['WeekendMorning BELOW']

In [140]:
DF1['LateNight Above%']=DF1['LateNight ABOVE']/DF1['LateNight Count']
DF1['LateNight Below%']=DF1['LateNight BELOW']/DF1['LateNight Count']
DF1['LateNight Score']=(DF1['LateNight ABOVE']*DF1['LateNight Above%'])-(DF1['LateNight BELOW']*DF1['LateNight Below%'])

DF1['LateNight(wknd) Above%']=DF1['LateNight(wknd) ABOVE']/DF1['LateNight(wknd) Count']
DF1['LateNight(wknd) Below%']=DF1['LateNight(wknd) BELOW']/DF1['LateNight(wknd) Count']
DF1['LateNight(wknd) Score']=(DF1['LateNight(wknd) ABOVE']*DF1['LateNight(wknd) Above%'])-(DF1['LateNight(wknd) BELOW']*DF1['LateNight(wknd) Below%'])

DF1['Overnight Above%']=DF1['Overnight ABOVE']/DF1['Overnight Count']
DF1['Overnight Below%']=DF1['Overnight BELOW']/DF1['Overnight Count']
DF1['Overnight Score']=(DF1['Overnight ABOVE']*DF1['Overnight Above%'])-(DF1['Overnight BELOW']*DF1['Overnight Below%'])

DF1['Overnight(wknd) Above%']=DF1['Overnight(wknd) ABOVE']/DF1['Overnight(wknd) Count']
DF1['Overnight(wknd) Below%']=DF1['Overnight(wknd) BELOW']/DF1['Overnight(wknd) Count']
DF1['Overnight(wknd) Score']=(DF1['Overnight(wknd) ABOVE']*DF1['Overnight(wknd) Above%'])-(DF1['Overnight(wknd) BELOW']*DF1['Overnight(wknd) Below%'])

DF1['Prime Above%']=DF1['Prime ABOVE']/DF1['Prime Count']
DF1['Prime Below%']=DF1['Prime BELOW']/DF1['Prime Count']
DF1['Prime Score']=(DF1['Prime ABOVE']*DF1['Prime Above%'])-(DF1['Prime BELOW']*DF1['Prime Below%'])

DF1['Prime(wknd) Above%']=DF1['Prime(wknd) ABOVE']/DF1['Prime(wknd) Count']
DF1['Prime(wknd) Below%']=DF1['Prime(wknd) BELOW']/DF1['Prime(wknd) Count']
DF1['Prime(wknd) Score']=(DF1['Prime(wknd) ABOVE']*DF1['Prime(wknd) Above%'])-(DF1['Prime(wknd) BELOW']*DF1['Prime(wknd) Below%'])

DF1['WeekdayDay Above%']=DF1['WeekdayDay ABOVE']/DF1['WeekdayDay Count']
DF1['WeekdayDay Below%']=DF1['WeekdayDay BELOW']/DF1['WeekdayDay Count']
DF1['WeekdayDay Score']=(DF1['WeekdayDay ABOVE']*DF1['WeekdayDay Above%'])-(DF1['WeekdayDay BELOW']*DF1['WeekdayDay Below%'])

DF1['WeekdayFringe Above%']=DF1['WeekdayFringe ABOVE']/DF1['WeekdayFringe Count']
DF1['WeekdayFringe Below%']=DF1['WeekdayFringe BELOW']/DF1['WeekdayFringe Count']
DF1['WeekdayFringe Score']=(DF1['WeekdayFringe ABOVE']*DF1['WeekdayFringe Above%'])-(DF1['WeekdayFringe BELOW']*DF1['WeekdayFringe Below%'])

DF1['WeekdayMorning Above%']=DF1['WeekdayMorning ABOVE']/DF1['WeekdayMorning Count']
DF1['WeekdayMorning Below%']=DF1['WeekdayMorning BELOW']/DF1['WeekdayMorning Count']
DF1['WeekdayMorning Score']=(DF1['WeekdayMorning ABOVE']*DF1['WeekdayMorning Above%'])-(DF1['WeekdayMorning BELOW']*DF1['WeekdayMorning Below%'])

DF1['WeekendDay Above%']=DF1['WeekendDay ABOVE']/DF1['WeekendDay Count']
DF1['WeekendDay Below%']=DF1['WeekendDay BELOW']/DF1['WeekendDay Count']
DF1['WeekendDay Score']=(DF1['WeekendDay ABOVE']*DF1['WeekendDay Above%'])-(DF1['WeekendDay BELOW']*DF1['WeekendDay Below%'])

DF1['WeekendMorning Above%']=DF1['WeekendMorning ABOVE']/DF1['WeekendMorning Count']
DF1['WeekendMorning Below%']=DF1['WeekendMorning BELOW']/DF1['WeekendMorning Count']
DF1['WeekendMorning Score']=(DF1['WeekendMorning ABOVE']*DF1['WeekendMorning Above%'])-(DF1['WeekendMorning BELOW']*DF1['WeekendMorning Below%'])

In [141]:
DF1=DF1.loc[:,('Title',
             'LateNight Count','LateNight ABOVE','LateNight NEUTRAL','LateNight BELOW','LateNight Above%','LateNight Score',
             'LateNight(wknd) Count','LateNight(wknd) ABOVE','LateNight(wknd) NEUTRAL','LateNight(wknd) BELOW','LateNight(wknd) Above%','LateNight(wknd) Score',
             'Overnight Count','Overnight ABOVE','Overnight NEUTRAL','Overnight BELOW','Overnight Above%','Overnight Score',
             'Overnight(wknd) Count','Overnight(wknd) ABOVE','Overnight(wknd) NEUTRAL','Overnight(wknd) BELOW','Overnight(wknd) Above%','Overnight(wknd) Score',
             'Prime Count','Prime ABOVE','Prime NEUTRAL','Prime BELOW','Prime Above%','Prime Score',
             'Prime(wknd) Count','Prime(wknd) ABOVE','Prime(wknd) NEUTRAL','Prime(wknd) BELOW','Prime(wknd) Above%','Prime(wknd) Score',
             'WeekdayDay Count','WeekdayDay ABOVE','WeekdayDay NEUTRAL','WeekdayDay BELOW','WeekdayDay Above%','WeekdayDay Score',
             'WeekdayFringe Count','WeekdayFringe ABOVE','WeekdayFringe NEUTRAL','WeekdayFringe BELOW','WeekdayFringe Above%','WeekdayFringe Score',
             'WeekdayMorning Count','WeekdayMorning ABOVE','WeekdayMorning NEUTRAL','WeekdayMorning BELOW','WeekdayMorning Above%','WeekdayMorning Score',
             'WeekendDay Count','WeekendDay ABOVE','WeekendDay NEUTRAL','WeekendDay BELOW','WeekendDay Above%','WeekendDay Score',
             'WeekendMorning Count','WeekendMorning ABOVE','WeekendMorning NEUTRAL','WeekendMorning BELOW','WeekendMorning Above%','WeekendMorning Score',)]

In [142]:
DF1.loc[DF1['LateNight Count']==0,('LateNight Count','LateNight ABOVE','LateNight NEUTRAL','LateNight BELOW','LateNight Above%','LateNight Score')]=''
DF1.loc[DF1['LateNight(wknd) Count']==0,('LateNight(wknd) Count','LateNight(wknd) ABOVE','LateNight(wknd) NEUTRAL','LateNight(wknd) BELOW','LateNight(wknd) Above%','LateNight(wknd) Score')]=''
DF1.loc[DF1['Overnight Count']==0,('Overnight Count','Overnight ABOVE','Overnight NEUTRAL','Overnight BELOW','Overnight Above%','Overnight Score')]=''
DF1.loc[DF1['Overnight(wknd) Count']==0,('Overnight(wknd) Count','Overnight(wknd) ABOVE','Overnight(wknd) NEUTRAL','Overnight(wknd) BELOW','Overnight(wknd) Above%','Overnight(wknd) Score')]=''
DF1.loc[DF1['Prime Count']==0,('Prime Count','Prime ABOVE','Prime NEUTRAL','Prime BELOW','Prime Above%','Prime Score')]=''
DF1.loc[DF1['Prime(wknd) Count']==0,('Prime(wknd) Count','Prime(wknd) ABOVE','Prime(wknd) NEUTRAL','Prime(wknd) BELOW','Prime(wknd) Above%','Prime(wknd) Score')]=''
DF1.loc[DF1['WeekdayDay Count']==0,('WeekdayDay Count','WeekdayDay ABOVE','WeekdayDay NEUTRAL','WeekdayDay BELOW','WeekdayDay Above%','WeekdayDay Score')]=''
DF1.loc[DF1['WeekdayFringe Count']==0,('WeekdayFringe Count','WeekdayFringe ABOVE','WeekdayFringe NEUTRAL','WeekdayFringe BELOW','WeekdayFringe Above%','WeekdayFringe Score')]=''
DF1.loc[DF1['WeekdayMorning Count']==0,('WeekdayMorning Count','WeekdayMorning ABOVE','WeekdayMorning NEUTRAL','WeekdayMorning BELOW','WeekdayMorning Above%','WeekdayMorning Score')]=''
DF1.loc[DF1['WeekendDay Count']==0,('WeekendDay Count','WeekendDay ABOVE','WeekendDay NEUTRAL','WeekendDay BELOW','WeekendDay Above%','WeekendDay Score')]=''
DF1.loc[DF1['WeekendMorning Count']==0,('WeekendMorning Count','WeekendMorning ABOVE','WeekendMorning NEUTRAL','WeekendMorning BELOW','WeekendMorning Above%','WeekendMorning Score')]=''

In [143]:
DF_CI=pd.merge(SummaryW,DF1, on='Title', how='left')

In [144]:
DF_CI

,Series/Film,Title,Above,Neutral,Below,Count,%Above CI,%Inside CI,%Below CI,Score,...,WeekendDay NEUTRAL,WeekendDay BELOW,WeekendDay Above%,WeekendDay Score,WeekendMorning Count,WeekendMorning ABOVE,WeekendMorning NEUTRAL,WeekendMorning BELOW,WeekendMorning Above%,WeekendMorning Score
0,Film,4GOT10,9.0,7.0,3.0,19.0,0.473684,0.368421,0.157895,3.789474,...,1.0,0.0,0.0,0.0,,,,,,
1,Film,ALONE IN THE DARK 2,2.0,8.0,4.0,14.0,0.142857,0.571429,0.285714,-0.857143,...,,,,,,,,,,
2,Film,Audition,4.0,7.0,4.0,15.0,0.266667,0.466667,0.266667,0.000000,...,,,,,,,,,,
3,Film,Bad Black and Beautiful,6.0,5.0,0.0,11.0,0.545455,0.454545,0.000000,3.272727,...,1.0,0.0,0.0,0.0,,,,,,
4,Film,Basket Case,1.0,2.0,6.0,9.0,0.111111,0.222222,0.666667,-3.888889,...,,,,,,,,,,
5,Film,Big Kill,13.0,2.0,2.0,17.0,0.764706,0.117647,0.117647,9.705882,...,,,,,,,,,,
6,Film,Black Cobra,4.0,0.0,0.0,4.0,1.000000,0.000000,0.000000,4.000000,...,,,,,,,,,,
7,Film,Black Fist,0.0,2.0,1.0,3.0,0.000000,0.666667,0.333333,-0.333333,...,2.0,1.0,0.0,-0.333333,,,,,,
8,Film,Black Gestapo,0.0,4.0,0.0,4.0,0.000000,1.000000,0.000000,0.000000,...,3.0,0.0,0.0,0.0,,,,,,
9,Film,Black Godfather,4.0,1.0,3.0,8.0,0.500000,0.125000,0.375000,0.875000,...,,,,,,,,,,
10,Film,Bruce's Deadly Fingers,2.0,0.0,0.0,2.0,1.000000,0.000000,0.000000,2.000000,...,,,,,,,,,,
11,Film,Dead or Alive,2.0,8.0,5.0,15.0,0.133333,0.533333,0.333333,-1.400000,...,,,,,,,,,,
12,Film,Dead or Alive 2,2.0,6.0,7.0,15.0,0.133333,0.400000,0.466667,-3.000000,...,,,,,,,,,,
13,Film,Deep Red,4.0,1.0,1.0,6.0,0.666667,0.166667,0.166667,2.500000,...,,,,,,,,,,
14,Film,Fox Style,1.0,10.0,5.0,16.0,0.062500,0.625000,0.312500,-1.500000,...,1.0,1.0,0.0,-0.5,,,,,,
15,Film,Gen Y Cops,1.0,4.0,10.0,15.0,0.066667,0.266667,0.666667,-6.600000,...,,,,,,,,,,
16,Film,Get Christie Love,2.0,7.0,4.0,13.0,0.153846,0.538462,0.307692,-0.923077,...,,,,,,,,,,
17,Film,Grandma's House,2.0,0.0,0.0,2.0,1.000000,0.000000,0.000000,2.000000,...,,,,,,,,,,
18,Film,Guy from Harlem (aka Good Guy From Harlem,3.0,4.0,0.0,7.0,0.428571,0.571429,0.000000,1.285714,...,,,,,,,,,,
19,Film,Head Hunter,5.0,4.0,5.0,14.0,0.357143,0.285714,0.357143,0.000000,...,,,,,,,,,,
20,Film,Kung Fu Traveler,1.0,6.0,1.0,8.0,0.125000,0.750000,0.125000,0.000000,...,2.0,0.0,0.333333,0.333333,,,,,,
21,Film,Kung Fu Traveler 2,0.0,6.0,0.0,6.0,0.000000,1.000000,0.000000,0.000000,...,1.0,0.0,0.0,0.0,,,,,,
22,Film,Lady Cocoa,12.0,3.0,0.0,15.0,0.800000,0.200000,0.000000,9.600000,...,2.0,0.0,0.0,0.0,,,,,,
23,Film,Miami Connection,4.0,2.0,5.0,11.0,0.363636,0.181818,0.454545,-0.818182,...,,,,,,,,,,
24,Film,On The Run,0.0,4.0,4.0,8.0,0.000000,0.500000,0.500000,-2.000000,...,,,,,,,,,,
25,Film,R100,2.0,6.0,3.0,11.0,0.181818,0.545455,0.272727,-0.454545,...,,,,,,,,,,
26,Film,Re-Animator,1.0,5.0,8.0,14.0,0.071429,0.357143,0.571429,-4.500000,...,,,,,,,,,,
27,Film,Samurai Cop 2: Deadly Vengeance,6.0,4.0,3.0,13.0,0.461538,0.307692,0.230769,2.076923,...,,,,,1.0,1.0,0.0,0.0,1.0,1.0
28,Film,Satan's Slave,0.0,1.0,7.0,8.0,0.000000,0.125000,0.875000,-6.125000,...,,,,,,,,,,
29,Film,Season of the Witch,3.0,3.0,0.0,6.0,0.500000,0.500000,0.000000,1.500000,...,,,,,,,,,,
30,Film,Shark,4.0,6.0,6.0,16.0,0.250000,0.375000,0.375000,-1.250000,...,,,,,,,,,,
31,Film,Silencer,5.0,7.0,2.0,14.0,0.357143,0.500000,0.142857,1.500000,...,,,,,,,,,,
32,Film,Sister Street Fighter,0.0,2.0,0.0,2.0,0.000000,1.000000,0.000000,0.000000,...,2.0,0.0,0.0,0.0,,,,,,
33,Film,Society,0.0,7.0,2.0,9.0,0.000000,0.777778,0.222222,-0.444444,...,,,,,,,,,,
34,Film,The Baron,0.0,3.0,0.0,3.0,0.000000,1.000000,0.000000,0.000000,...,1.0,0.0,0.0,0.0,,,,,,
35,Film,The Black Brigade,14.0,8.0,4.0,26.0,0.538462,0.307692,0.153846,6.923077,...,,,,,,,,,,
36,Film,The Cat o' Nine Tails,0.0,3.0,6.0,9.0,0.000000,0.333333,0.666667,-4.000000,...,,,,,,,,,,
37,Film,The Crazies,2.0,9.0,9.0,20.0,0.100000,0.450000,0.450000,-3.850000,...,,,,,,,,,,
38,Film,The Driller Killer,0.0,4.0,8.0,12.0,0.000000,0.333333,0.666667,-5.333333,...,,,,,,,,,,
39,Film,The Final Comedown,1.0,1.0,5.0,7.0,0.142857,0.142857,0.714286,-3.428571,...,,,,,,,,,,
40,Film,The Hills Have Eyes,9.0,0.0,0.0,9.0,1.000000,0.000000,0.000000,9.000000,...,,,,,,,,,,
41,Film,The Hills Have Eyes Part 2,7.0,3.0,2.0,12.0,0.583333,0.250000,0.166667,3.750000,...,,,,,,,,,,
42,Film,The Mutilator,0.0,1.0,5.0,6.0,0.000000,0.166667,0.833333,-4.166667,...,,,,,,,,,,
43,Film,The White Storm 2: Drug Lords,9.0,5.0,10.0,24.0,0.375000,0.208333,0.416667,-0.791667,...,,,,,,,,,,
44,Film,Torso,1.0,0.0,4.0,5.0,0.200000,0.000000,0.800000,-3.000000,...,,,,,,,,,,
45,Series,Correctamundo!,32.0,41.0,29.0,102.0,0.313725,0.401961,0.284314,1.794118,...,15.0,1.0,0.333333,2.625,5.0,2.0,3.0,0.0,0.4,0.8
46,Series,Cutting Crew,0.0,9.0,11.0,20.0,0.000000,0.450000,0.550000,-6.050000,...,9.0,11.0,0.0,-6.05,,,,,,
47,Series,Director's Chair,9.0,26.0,9.0,44.0,0.204545,0.590909,0.204545,0.000000,...,14.0,7.0,0.0,-2.333333,18.0,8.0,8.0,2.0,0.444444,3.333333
48,Series,El Rey Nation,66.0,82.0,84.0,232.0,0.284483,0.353448,0.362069,-11.637931,...,,,,,,,,,,
49,Series,El Rey's Top 5,10.0,23.0,29.0,62.0,0.161290,0.370968,0.467742,-11.951613,...,11.0,20.0,0.0,-12.903226,,,,,,
50,Series,Ip Man,50.0,114.0,44.0,208.0,0.240385,0.548077,0.211538,2.711538,...,33.0,0.0,0.352941,6.352941,,,,,,
51,Series,June Castro's Fight Fit,0.0,25.0,2.0,27.0,0.000000,0.925926,0.074074,-0.148148,...,4.0,0.0,0.0,0.0,21.0,0.0,19.0,2.0,0.0,-0.190476
52,Series,Keep Bleeding with Mike Escamilla,2.0,11.0,0.0,13.0,0.153846,0.846154,0.000000,0.307692,...,4.0,0.0,0.0,0.0,8.0,2.0,6.0,0.0,0.25,0.5
53,Series,Maria!,33.0,66.0,74.0,173.0,0.190751,0.381503,0.427746,-25.358382,...,,,,,,,,,,
54,Series,The Camacho Experiment,0.0,3.0,0.0,3.0,0.000000,1.000000,0.000000,0.000000,...,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
55,Series,The Chuey Martinez Show,13.0,14.0,14.0,41.0,0.317073,0.341463,0.341463,-0.658537,...,,,,,,,,,,
56,Series,United Tacos of America,3.0,18.0,31.0,52.0,0.057692,0.346154,0.596154,-18.307692,...,1.0,3.0,0.0,-2.25,16.0,3.0,8.0,5.0,0.1875,-1.0
57,Series,Vampiro: Unleashed,0.0,15.0,6.0,21.0,0.000000,0.714286,0.285714,-1.714286,...,,,,,4.0,0.0,1.0,3.0,0.0,-2.25

# Summary

In [145]:
dfminsum1= dfmin.loc[:,('Series/Film','Title', 'Dayparts_Start',
                        'Performance - August(Daypart avg)','Performance - September(Daypart avg)' )]
dfminsum2= dfmin.loc[:, ('Series/Film','Title','Dayparts_End',
                         'Performance2 - August(Daypart avg)','Performance2 - September(Daypart avg)' )]

dfsessum1= dfsessD.loc[:,('Series/Film','Title', 'Dayparts_Start',
                          'Performance - August(Daypart avg)','Performance - September(Daypart avg)',
                          'Session Duration' )]
dfsessum2= dfsessD.loc[:, ('Series/Film','Title','Dayparts_End', 
                           'Performance2 - August(Daypart avg)' ,'Performance2 - September(Daypart avg)',
                           'Session Duration')]

In [146]:
dfminsum1.rename(columns={'Dayparts_Start':'Daypart'}, inplace=True)
dfminsum2.rename(columns={'Dayparts_End':'Daypart',
                         'Performance2 - August(Daypart avg)': 'Performance - August(Daypart avg)',
                         'Performance2 - September(Daypart avg)': 'Performance - September(Daypart avg)'}, inplace=True)

dfsessum1.rename(columns={'Dayparts_Start':'Daypart'}, inplace=True)
dfsessum2.rename(columns={'Dayparts_End':'Daypart',
                         'Performance2 - August(Daypart avg)': 'Performance - August(Daypart avg)',
                         'Performance2 - September(Daypart avg)': 'Performance - September(Daypart avg)'
                         }, inplace=True)

In [147]:
dfminsum= dfminsum1.append(dfminsum2)
dfsessum= dfsessum1.append(dfsessum2)

In [148]:
dfminsum= dfminsum.groupby(['Title','Daypart','Series/Film']).mean().reset_index()
dfsessum= dfsessum.groupby(['Title','Daypart','Series/Film']).mean().reset_index()

In [149]:
DF.sort_values(by=['TS','Hour(24-Pac)'], inplace=True)

In [150]:
dfmin

,Series/Film,Length_minutes,Title,Dayparts_Start,Length_minutes_DP1,Performance - August(Daypart avg),Performance - September(Daypart avg),Dayparts_End,Length_minutes_DP2,Performance2 - August(Daypart avg),Performance2 - September(Daypart avg),TS,Minutes per min,Minutes_Second Daypart,Minutes per min (avg)
0,Series,47.034167,Maria!,Overnight,47.034167,0.704529,0.538580,Overnight,0.000000,NaN,NaN,2021-09-01 00:02:01.000,238.333333,NaN,238.333333
1,Series,49.467667,Maria!,Overnight,49.467667,0.898740,0.713883,Overnight,0.000000,NaN,NaN,2021-09-01 00:49:03.050,265.488568,NaN,265.488568
2,Series,25.267000,The Chuey Martinez Show,Overnight,25.267000,0.930899,0.742911,Overnight,0.000000,NaN,NaN,2021-09-01 01:38:31.110,269.985224,NaN,269.985224
3,Film,100.835667,The Hills Have Eyes,Overnight,56.214500,0.613111,0.456063,Weekday Morning,44.621167,0.716865,0.729136,2021-09-01 02:03:47.130,225.550979,225.550979,225.550979
4,Film,105.265000,The Hills Have Eyes Part 2,Weekday Morning,105.265000,0.033943,0.041333,Weekday Morning,0.000000,NaN,NaN,2021-09-01 03:44:37.270,135.832898,NaN,135.832898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,Series,51.667667,Ip Man,Prime,8.099500,-0.524882,-0.345179,Late Night,43.568167,0.267760,0.916537,2021-09-30 19:51:54.030,235.298994,235.298994,235.298994
795,Series,51.116167,Ip Man,Late Night,51.116167,-0.306813,0.047926,Late Night,0.000000,NaN,NaN,2021-09-30 20:43:34.090,128.656948,NaN,128.656948
796,Series,51.387167,Ip Man,Late Night,51.387167,-0.407036,-0.103586,Late Night,0.000000,NaN,NaN,2021-09-30 21:34:41.060,110.055364,NaN,110.055364
797,Series,49.378833,Ip Man,Late Night,33.928500,-0.233655,0.158523,Overnight,15.450333,0.017249,-0.081788,2021-09-30 22:26:04.290,142.235371,142.235371,142.235371
798,Series,44.537500,Maria!,Overnight,44.537500,0.352061,0.220428,Overnight,0.000000,NaN,NaN,2021-09-30 23:15:27.020,189.050000,NaN,189.050000

In [151]:
#Change Date****************************************************************************
output= pd.ExcelWriter('ElRey_Sep_30_out.xlsx', engine='xlsxwriter')
DF.to_excel(output, sheet_name= 'DF',index=False)
DF_CI.to_excel(output, sheet_name= 'CI Summary',index=False)
dfmin.to_excel(output, sheet_name='Minutes', index=False)
dfminsum.to_excel(output, sheet_name='Minutes_Summary',index=False)
dfsessD.to_excel(output, sheet_name='Session Duration', index= False)
dfsessum.to_excel(output, sheet_name='Session Duration Summary',index=False)
Amagi_DPA.to_excel(output, sheet_name='Daypart Avrgs', index=False)
output.save()